### ISSUE TITLE
Add calendar feed as event source

### ISSUE THREAD

**Issue by danwchan** [AnarchoTechNYC/NYCAnarchistEvents#10]
Please add the following event source to the calendar: [Biotech Without Borders](https://calendar.google.com/calendar/ical/c_p5vmlisfi6tgjrtsmsbnpupcac%40group.calendar.google.com/public/basic.ics)

**Comment by fabacab** [comment]
Is that the same as the [Biotech Without Borders Meetup Group](https://www.meetup.com/biotech-without-borders/)? Most of the events appear very similar if not identical and are at the same date and time (`DTSTART` value). However, all of these events are in the past, so adding this feed would not actually produce a new listing.

Perhaps consider re-suggesting this when there are more upcoming events?

**Comment by danwchan** [comment]
Yes it is the same. Although our automation does not allow for automatic cross posts between the Google Calendar and the Meetup group. OK but I understand wanting not to have past events imported. 

When we have some upcoming events I'll open an issue to have the Meetup iCalendar feed imported.

Thanks,
