### ISSUE TITLE
Add calendar feed as event source

### ISSUE THREAD

**Issue by sam-slate** [AnarchoTechNYC/NYCAnarchistEvents#19]
Please add the following event source to the calendar: https://calendar.google.com/calendar/u/0/embed?src=32aa4c652b09effa13fca2b4547b7120b94321fecffcb7bb5c66e5741ba8db12@group.calendar.google.com&ctz=America/New_York

**Comment by fabacab** [comment]
> Please add the following event source to the calendar: https://calendar.google.com/calendar/u/0/embed?src=32aa4c652b09effa13fca2b4547b7120b94321fecffcb7bb5c66e5741ba8db12@group.calendar.google.com&ctz=America/New_York

There only seems to be one event on this calendar. It's even at a venue that is already listed.

![Screenshot_20231021-235501](https://github.com/AnarchoTechNYC/NYCAnarchistEvents/assets/18677/c8fcf703-0170-46bf-93b1-b03908eaa6c9)
