### ISSUE TITLE
Add calendar feed https://calendar.google.com/calendar/u/2/r?tab=mc&pli=1 as event source

### ISSUE THREAD

**Issue by urbancowgrrl** [AnarchoTechNYC/NYCAnarchistEvents#7]
Please add the following event source to the calendar: [https://calendar.google.com/calendar/u/2/r?tab=mc&pli=1]

**Comment by urbancowgrrl** [comment]
https://calendar.google.com/event?action=TEMPLATE&tmeid=MDM5aWVwMWs0MnA5OXVlcmQyYWlyOHZoZXAgc2NyaXB0dXJlYnJpQG0&tmsrc=scripturebri%40gmail.com

**Comment by urbancowgrrl** [comment]
https://calendar.google.com/calendar/u/2/r?tab=mc&pli=1

**Comment by fabacab** [comment]
I cannot add private calendars (calendars that are not public). [Make a public calendar](https://support.google.com/calendar/answer/37083).
