### ISSUE TITLE
https://calendar.google.com/calendar/u/2?cid=YWxya20zYWQybmllamgxbmx0MXFidTFzODhAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQAdd calendar feed as event source

### ISSUE THREAD

**Issue by urbancowgrrl** [AnarchoTechNYC/NYCAnarchistEvents#9]
Please add the following event source to the calendar: [https://calendar.google.com/calendar/u/2?cid=YWxya20zYWQybmllamgxbmx0MXFidTFzODhAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ]

@fabacab think this is the right link, thank you !

**Comment by fabacab** [comment]
So, this might not make sense to you but for my own posterity I'm going to explain to future me tersely why I'm not adding this feed right now:

```
curl -L $(echo -n 'https://calendar.google.com/calendar/u/2?cid=YWxya20zYWQybmllamgxbmx0MXFidTFzODhAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ' | cut -d '=' -f 2 | tr -d '\n' | base64 --decode | cat <(echo -n 'https://calendar.google.com/calendar/ical/') - <(echo -n 'm/public/basic.ics'))
```

produces only 1 event. A single event is not something I'm going to add a whole event source feed for, that would be prohibitively suboptimal from a performance standpoint.

I can add individual one-off events, though, so I'll do that.

I'm not sure what "Ear Ear" is, either (`… | grep X-WR-CALNAME` from above). If it's an organization producing events regularly, point us to a Web site at least, and we'll check it out over time.
